version: '3.5'

services:
  att-fe-app:
    image: "att/demo-fe"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    container_name: att-fe-app
    command: npm start
    environment:
      - NODE_ENV=development
